# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'ac9ef43d-5e52-40a8-a3ae-09d4d3dd8a78'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Grand.Web.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'grandnode/grandnode2'
    command: 'buildAndPush'
    tags: |
      latest
    Dockerfile: '**/Dockerfile'